name: CI Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake qt6-base-dev qt6-base-dev-tools

      - name: Set up vcpkg on Windows
        if: matrix.os == 'windows-latest'
        uses: lukka/get-vcpkg@v20

      - name: Install Qt6 on Windows
        if: matrix.os == 'windows-latest'
        run: |
          "${{ env.VCPKG_ROOT }}/vcpkg" install qt6-base:x64-windows

      - name: Configure CMake on Linux
        if: matrix.os == 'ubuntu-latest'
        run: cmake -S . -B build

      - name: Configure CMake on Windows
        if: matrix.os == 'windows-latest'
        run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: cmake --build build --config Release --parallel